### ISSUE TITLE
Possible Reflected Cross-Site Scripting (rXSS)

### ISSUE THREAD

**Issue by ebelties** [paynl/zencart-plugin#1]
Parameter `order_id` word direct geprint op de pagina zonder bescherming.
https://github.com/paynl/zencart-plugin/blob/fbe437995275fed5f832882352561bfec4838b42/ext/modules/payment/paynl/notify.php#L37

  
Voorgestelde oplossing:
```php
echo "TRUE|Exchange processed " . htmlentities ($_REQUEST['order_id']);
```

**Comment by IvoWams** [comment]
Lijkt erop dat deze files ook niet (meer) gebruikt worden ?
